spring:
  application:
    name: g2-scheduler
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPINRG_DATASOURCE_URL:jdbc:mysql://localhost:3306/g2_scheduler?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=GMT%2B8}
    username: ${SPRING_DATASOURCE_USERNAME:omsdev}
    password: ${SPRING_DATASOURCE_PASSWORD:omsdev}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}

mybatis:
  config-location: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
